  CREATE TABLE "AXGPMS_EXPENSES" 
   (	"PROJECT_NUMBER" VARCHAR2(100),
	"EXPENSE_TYPE" VARCHAR2(100),
	"RAW_COST" NUMBER(2,10),
	"SESSION_ID" NUMBER,
	"STATUS" VARCHAR2(100),
	"EXPENSE_COST" NUMBER(10,2)
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 10 NOCOMPRESS LOGGING
  TABLESPACE "DATA"