  CREATE TABLE "AXGPMS_PROJECT" 
   (	"PROJECT_NUMBER" VARCHAR2(100),
	"PROJECT_NAME" VARCHAR2(100),
	"STATUS" VARCHAR2(20),
	"OWNER" VARCHAR2(50)
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 10 NOCOMPRESS LOGGING
  TABLESPACE "DATA"