  CREATE TABLE "AXXML_TAB" 
   (	"ID" NUMBER,
	"XML_DATA" "PUBLIC"."XMLTYPE",
	"VC2_DATA" VARCHAR2(32000),
	"XML_CLOB" CLOB,
	"SESSION_ID" NUMBER,
	"SEQ" NUMBER GENERATED ALWAYS AS IDENTITY
 MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOT NULL ENABLE,
	"TS" TIMESTAMP(6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 10 NOCOMPRESS LOGGING
  TABLESPACE "DATA"
 XMLTYPE COLUMN "XML_DATA"  STORE AS SECUREFILE BINARY XML  (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING NOCOMPRESS KEEP_DUPLICATES ) ALLOW NONSCHEMA DISALLOW ANYSCHEMA
 LOB ("XML_CLOB") STORE AS SECUREFILE  (
  TABLESPACE "DATA" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING NOCOMPRESS KEEP_DUPLICATES )