  CREATE TABLE "GPMS_PROFILE_OPTIONS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY
 MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOT NULL ENABLE,
	"PROFILE_OPTION" VARCHAR2(100),
	"VALUE" VARCHAR2(100),
	"ENABLED" VARCHAR2(5),
	"CREATED_DATE" DATE,
	"EXPIRY_DATE" DATE,
	CONSTRAINT "GPMS_PROFILE_OPTIONS_PK" PRIMARY KEY ("ID")
  USING INDEX
  PCTFREE 10 INITRANS 20 MAXTRANS 255 LOGGING
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 10 NOCOMPRESS LOGGING
  TABLESPACE "DATA"