  CREATE TABLE "MA_APPROVAL_INVOICES" 
   (	"TASKID" VARCHAR2(4000),
	"TASKNUMBER" VARCHAR2(1000),
	"TASK_DEFINITION_NAME" VARCHAR2(4000),
	"PRIORITY" NUMBER,
	"TITLE" VARCHAR2(4000),
	"IDENTIFICATION_KEY" NUMBER,
	"CONTRACT_NUMBER" VARCHAR2(1000),
	"INVOICE_NUM" NUMBER,
	"INVOICE_STATUS_CODE" VARCHAR2(1000),
	"ASSIGNEE" VARCHAR2(2000),
	"ASSIGNEE_DISPLAY_NAME" VARCHAR2(2000),
	"INVOICE_CURRENCY_CODE" VARCHAR2(100),
	"INVOICE_DATE" VARCHAR2(1000),
	"INVOICE_AMOUNT" NUMBER,
	"WRITE_OFF_AMOUNT" NUMBER,
	"BILL_CUSTOMER_NAME" VARCHAR2(1000),
	"BILL_CUST_ACCT_NUM" VARCHAR2(1000),
	"BILL_CUST_ACCT_NAME" VARCHAR2(1000),
	"BILL_CUST_SITE" VARCHAR2(1000)
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 10 NOCOMPRESS LOGGING
  TABLESPACE "DATA"