  CREATE TABLE "PROGRESS_ENTRIES" 
   (	"PERCENTAGE" NUMBER,
	"MESSAGE" VARCHAR2(100),
	"CREATED_DATE" TIMESTAMP(6),
	"USER_EMAIL" VARCHAR2(100)
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 10 NOCOMPRESS LOGGING
  TABLESPACE "DATA"