  CREATE TABLE "PROGRESS_BAR_ENTRIES" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY
 MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOT NULL ENABLE,
	"MODULE" VARCHAR2(100),
	"SEQ" NUMBER,
	"MESSAGE" VARCHAR2(200),
	"PERCENTAGE" NUMBER,
	CONSTRAINT "PROGRESS_BAR_ENTRIES_CON" UNIQUE ("SEQ","MODULE")
  USING INDEX
  PCTFREE 10 INITRANS 20 MAXTRANS 255 LOGGING
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 10 NOCOMPRESS LOGGING
  TABLESPACE "DATA"