  CREATE TABLE "XXGPMS_INTERPROJECTS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY
 MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOT NULL ENABLE,
	"PROJECT_NUMBER" VARCHAR2(100 CHAR),
	"LABOR_WIP" NUMBER,
	"FEES_WIP" NUMBER,
	"HARD_WIP" NUMBER,
	"SOFT_WIP" NUMBER,
	"SESSION_ID" NUMBER,
	CONSTRAINT "XXGPMS_INTERPROJECTS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX
  PCTFREE 10 INITRANS 20 MAXTRANS 255 LOGGING
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 10 NOCOMPRESS LOGGING
  TABLESPACE "DATA"