  CREATE TABLE "XXGPMS_EXP_TYPES" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY
 MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOT NULL ENABLE,
	"EXPENDITURE_TYPE_NAME" VARCHAR2(1000 CHAR),
	"EXPENDITURE_TYPE_ID" NUMBER,
	"SESSION_ID" NUMBER,
	CONSTRAINT "XXGPMS_EXP_TYPES_ID_PK" PRIMARY KEY ("ID")
  USING INDEX
  PCTFREE 10 INITRANS 20 MAXTRANS 255 LOGGING
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 10 NOCOMPRESS LOGGING
  TABLESPACE "DATA"