  CREATE TABLE "XXGPMS_PROJECTS" 
   (	"PROJECT_NUMBER" VARCHAR2(100),
	"TASK_ID" VARCHAR2(4000),
	"SESSION_ID" NUMBER
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 10 NOCOMPRESS LOGGING
  TABLESPACE "DATA"