  CREATE TABLE "XXGPMS_MATTER_CREDITS" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY
 MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER NOCYCLE NOT NULL ENABLE,
	"MATTER_NUMBER" VARCHAR2(4000 CHAR),
	"CREDIT_TYPE" VARCHAR2(1000 CHAR),
	"BILLED" NUMBER,
	"PAID" NUMBER,
	"APPLIED" NUMBER,
	"AVAILABLE" NUMBER,
	"SESSION_ID" NUMBER,
	"INVOICE_CURRENCY_CODE" VARCHAR2(100),
	CONSTRAINT "XXGPMS_MATTER_CREDITS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX
  PCTFREE 10 INITRANS 20 MAXTRANS 255 LOGGING
  TABLESPACE "DATA"  ENABLE
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 10 NOCOMPRESS LOGGING
  TABLESPACE "DATA"