  CREATE TABLE "XXGPMS_PROJECT_INVOICES" 
   (	"INVOICE_ID" NUMBER,
	"CONTRACT_ID" NUMBER,
	"INVOICE_CURRENCY_CODE" VARCHAR2(100),
	"REQUEST_ID" NUMBER,
	"CREATED_BY" VARCHAR2(100),
	"CREATION_DATE" VARCHAR2(100),
	"INVOICE_LINE_ID" NUMBER,
	"INVOICE_CURR_BILLED_AMT" NUMBER,
	"INVOICE_DATE" VARCHAR2(100),
	"ORG_ID" NUMBER,
	"SESSION_ID" NUMBER,
	"WRITE_OFF_AMOUNT" NUMBER
   ) SEGMENT CREATION DEFERRED
  PCTFREE 10 PCTUSED 40 INITRANS 10 NOCOMPRESS LOGGING
  TABLESPACE "DATA"