CREATE OR REPLACE EDITIONABLE PACKAGE "MA_UTIL" as
  procedure fetch_invoices;
  PROCEDURE WEBSERVICE_CALL(P_WEB_SERVICE_TYPE VARCHAR2,P_REQUEST CLOB,P_RESPONSE_CODE OUT NUMBER,P_RESPONSE OUT CLOB);
  PROCEDURE MASS_APPROVE_INVOICES (P_TASK_NUMBERS VARCHAR2,P_RESPONSE CLOB);
  PROCEDURE MASS_REJECT_INVOICES (P_TASK_NUMBERS VARCHAR2,P_JUSTIFICATION VARCHAR2,P_RESPONSE CLOB);
end "MA_UTIL";
/