CREATE OR REPLACE EDITIONABLE PROCEDURE "WEBSERVICE_LOGGER" (P_URL VARCHAR2,P_REQUEST CLOB,P_RESPONSE CLOB,P_RESPONSE_CODE NUMBER)
IS
  PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  INSERT INTO WEBSERVICE_LOG(URL,REQUEST,RESPONSE,RESPONSE_CODE) VALUES (P_URL,P_REQUEST,P_RESPONSE,P_RESPONSE_CODE);
  COMMIT;
END;
/