CREATE OR REPLACE EDITIONABLE PROCEDURE "WIP_LOGGER_PROC" (P_MESSAGE_VC IN VARCHAR2 DEFAULT NULL,
P_MESSAGE_CLOB IN VARCHAR2 DEFAULT NULL)
IS 
PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
  INSERT INTO WIP_LOGGER(MESSAGE_VC,MESSAGE_CLOB)
  VALUES (P_MESSAGE_VC,P_MESSAGE_CLOB);
  COMMIT;
END;
/