CREATE OR REPLACE EDITIONABLE PROCEDURE "XX_JWT_USERNAME" 
 is    
i number;  
  
begin  
i := 0;  
  
DELETE FROM XXGPMS_PROJECT_COSTS
WHERE  SESSION_ID = V('APP_SESSION');
DELETE FROM XXGPMS_PROJECT_WIP_CATEGORY
WHERE  SESSION_ID = V('APP_SESSION');
         
        DELETE FROM XXGPMS_PROJECT_EVENTS
        WHERE  SESSION_ID = V('APP_SESSION');
         
        DELETE FROM XXGPMS_PROJECT_CONTRACT
        WHERE  SESSION_ID = V('APP_SESSION');
        DELETE FROM XXGPMS_PROJECT_RATES
        WHERE  SESSION_ID = V('APP_SESSION');
        DELETE FROM xxgpms_project_invoices
        WHERE  SESSION_ID = V('APP_SESSION');
        DELETE FROM xxgpms_project_invoice_history
        WHERE  SESSION_ID = V('APP_SESSION');
        --  DELETE FROM XXGPMS_PROJECTS
        -- WHERE  SESSION_ID = V('APP_SESSION');
         
        DELETE FROM XXGPMS_MATTER_CREDITS
        WHERE  SESSION_ID = V('APP_SESSION');
        DELETE FROM XXGPMS_INTERPROJECTS
         WHERE  SESSION_ID = V('APP_SESSION');
         
        DELETE FROM AXXML_TAB; 
        DELETE FROM SPELL_CHECK;
        DELETE FROM  XXGPMS_EXP_TYPES; 
        -- DELETE FROM  XXGPMS_; 
                
        DELETE FROM SPELL_CHECKER_DTL; 
         
  
end;
/